server:
  port: 8001

spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/stationdb
    url: jdbc:postgresql://station-controller-db:5432/stationdb
    username: station
    password: changeme
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 60000
      initialization-fail-timeout: 0

  jpa:
    hibernate:
      ddl-auto: none   # Liquibase управляет схемой
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect


  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
    parameters:
      retryAttempts: 10
      retryDelay: 5s

  kafka:
#    bootstrap-servers: localhost:29092
    bootstrap-servers: kafka:9092
    consumer:
      group-id: station-controller-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: java.util.Map
        max.block.ms: 5000
        request.timeout.ms: 5000
        delivery.timeout.ms: 10000
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
        enable.idempotence: true
        acks: all
        max.in.flight.requests.per.connection: 1
        retries: 2147483647
        delivery.timeout.ms: 120000
        transactional.id: station-state-producer
    properties:
      security.protocol: PLAINTEXT

logging:
  level:
    root: INFO
    charg.ing.stations: WARN
    org.springframework.kafka: DEBUG
    org.apache.kafka: WARN

management:
  endpoints:
    web:
      exposure:
        include:
          - beans