package charg.ing.stations.event.enums;

public enum UserEventType {
    USER_REGISTERED,
    USER_UPDATED,
    USER_DEACTIVATED,
    USER_ACTIVATED,
    EMAIL_VERIFICATION_REQUESTED,
    EMAIL_VERIFIED,
    PHONE_VERIFICATION_REQUESTED,
    PHONE_VERIFIED,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET,
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    ROLE_CHANGED,
    PROFILE_UPDATED,
    STATION_FAULTED
}