server:
  port: 8000

spring:
  application:
    name: station-integration-service

topics:
  ocpp:
    responses: ocpp.responses


management:
  server:
    port: ${server.port}
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus,beans"
      base-path: /actuator

logging:
  level:
    root: INFO
    citrine.os.station: WARN
    org.springframework.kafka: DEBUG
    org.apache.kafka: WARN
    org.springframework.web: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
    reactor.netty.http.client: DEBUG